---
- name: Install bind9
  hosts: lnx
  become: true

  vars:
    config_dir: ../config

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install BIND9 package
      ansible.builtin.apt:
        name:
          - bind9
          - bind9utils
          - bind9-doc
        state: present

    - name: Copy BIND9 configuration file
      ansible.builtin.copy:
        src: "{{ config_dir }}/bind/named"
        dest: /etc/default/named
        mode: '0644'

    - name: Copy BIND9 configuration file
      ansible.builtin.copy:
        src: "{{ config_dir }}/bind/named.conf.local"
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: '0644'

    - name: Copy BIND9 configuration options file
      ansible.builtin.copy:
        src: "{{ config_dir }}/bind/named.conf.options"
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: '0644'

    - name: Copy BIND9 zone file
      ansible.builtin.copy:
        src: "{{ config_dir }}/bind/db.stembayo.id"
        dest: /etc/bind/db.stembayo.id
        owner: root
        group: bind
        mode: '0644'

    - name: Copy BIND9 reverse zone file
      ansible.builtin.copy:
        src: "{{ config_dir }}/bind/db.172.16.18"
        dest: /etc/bind/db.172.16.18
        owner: root
        group: bind
        mode: '0644'

    - name: Restart bind9 service
      ansible.builtin.systemd_service:
        name: bind9
        state: restarted
        daemon_reload: true
