---
- name: Install nginx
  hosts: lnx
  become: true

  vars:
    web_root: /var/www
    config_dir: ../config
    file_dir: ../files
    htpasswd_credentials:
      - { username: "competitor", password: "Skills39" }

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install nginx package
      ansible.builtin.apt:
        name: nginx
        state: present

    # lnx.stembayo.id
    - name: Create lnx.stembayo.id directory
      ansible.builtin.file:
        path: "{{ web_root }}/lnx.stembayo.id"
        state: directory
        mode: "0755"

    - name: Copy html file for lnx.stembayo.id
      ansible.builtin.copy:
        src: "{{ file_dir }}/html/lnx.html"
        dest: "{{ web_root }}/lnx.stembayo.id/index.html"
        mode: "0755"

    - name: Copy configuration file for lnx.stembayo.id
      ansible.builtin.copy:
        src: "{{ config_dir }}/nginx/vhost/lnx.stembayo.id"
        dest: /etc/nginx/sites-available/lnx.stembayo.id
        mode: "0755"

    - name: Enable lnx.stembayo.id
      ansible.builtin.file:
        src: /etc/nginx/sites-available/lnx.stembayo.id
        dest: /etc/nginx/sites-enabled/lnx.stembayo.id
        state: link
      notify: Restart Nginx

    # stembayo.id
    - name: Create stembayo.id directory
      ansible.builtin.file:
        path: "{{ web_root }}/stembayo.id"
        state: directory
        mode: "0755"

    - name: Copy html file for stembayo.id
      ansible.builtin.copy:
        src: "{{ file_dir }}/html/stembayo.html"
        dest: "{{ web_root }}/stembayo.id/index.html"
        mode: "0755"

    - name: Copy configuration file for stembayo.id
      ansible.builtin.copy:
        src: "{{ config_dir }}/nginx/vhost/stembayo.id"
        dest: /etc/nginx/sites-available/stembayo.id
        mode: "0755"

    - name: Enable stembayo.id
      ansible.builtin.file:
        src: /etc/nginx/sites-available/stembayo.id
        dest: /etc/nginx/sites-enabled/stembayo.id
        state: link
      notify: Restart Nginx

    # basic-auth.stembayo.id

    - name: Create basic-auth.stembayo.id directory
      ansible.builtin.file:
        path: "{{ web_root }}/basic-auth.stembayo.id"
        state: directory
        mode: "0755"

    - name: Copy html file for basic-auth.stembayo.id
      ansible.builtin.copy:
        src: "{{ file_dir }}/html/basic-auth.html"
        dest: "{{ web_root }}/basic-auth.stembayo.id/index.html"
        mode: "0755"

    - name: Copy configuration file for basic-auth.stembayo.id
      ansible.builtin.copy:
        src: "{{ config_dir }}/nginx/vhost/basic-auth.stembayo.id"
        dest: /etc/nginx/sites-available/basic-auth.stembayo.id
        mode: "0755"

    - name: Generate .htpasswd file
      ansible.builtin.command: "printf '%s:' '{{ item.username }}' >> test; echo '{{ item.password }}' | openssl passwd -apr1 -stdin >> test"
      loop: "{{ htpasswd_credentials }}"
      register: generate_htpasswd_out
      changed_when: generate_htpasswd_out.rc != 0

    - name: Enable basic-auth.stembayo.id
      ansible.builtin.file:
        src: /etc/nginx/sites-available/basic-auth.stembayo.id
        dest: /etc/nginx/sites-enabled/basic-auth.stembayo.id
        state: link
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        daemon_reload: true
