---
- name: Install vsftpd
  hosts: lnx
  become: true

  vars:
    config_dir: ../config
    usernames:
      - competitor

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install vsftpd package
      ansible.builtin.apt:
        name: vsftpd
        state: present

    - name: Create backup configuration
      ansible.builtin.copy:
        remote_src: true
        src: /etc/vsftpd.conf
        dest: /etc/vsftpd.conf.backup
        mode: '0644'

    - name: Add user to userlist
      ansible.builtin.copy:
        dest: /etc/vsftpd.userlist
        content: |
          {% for user in usernames %}
          {{ user }}
          {% endfor %}
        mode: '0644'

    - name: Create share directory
      ansible.builtin.file:
        path: "/home/{{ item }}/share"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: '0755'
      loop: "{{ usernames }}"

    - name: Remove vsftpd.conf
      ansible.builtin.file:
        path: /etc/vsftpd.conf
        state: absent

    - name: Copy vsftpd.conf
      ansible.builtin.copy:
        src: "{{ config_dir }}/vsftpd/vsftpd.conf"
        dest: /etc/vsftpd.conf
        mode: '0644'

    - name: Restart vsftpd service
      ansible.builtin.systemd_service:
        name: vsftpd
        state: restarted
        daemon_reload: true
